import { jsPDF } from "jspdf"
import "jspdf-autotable"

export const generatePDF = (code: string, title = "Code Snippet") => {
  // Create a new PDF document
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  })

  // Set font
  doc.setFont("helvetica", "normal")

  // Add title
  doc.setFontSize(18)
  doc.text(title, 20, 20)

  // Add subtitle
  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text("Generated by Code Muse - Your Intelligent Coding Companion", 20, 30)

  // Add timestamp
  const date = new Date().toLocaleString()
  doc.setFontSize(10)
  doc.text(`Generated on: ${date}`, 20, 40)

  // Add horizontal line
  doc.setDrawColor(200, 200, 200)
  doc.line(20, 45, 190, 45)

  // Add code content with line breaks
  doc.setFontSize(10)
  doc.setTextColor(0, 0, 0)

  // Split code into lines
  const lines = code.split("\n")
  let y = 55

  // Add each line to the PDF
  lines.forEach((line) => {
    // Check if line is too long and needs wrapping
    if (line.length > 100) {
      const chunks = []
      for (let i = 0; i < line.length; i += 100) {
        chunks.push(line.substring(i, i + 100))
      }

      chunks.forEach((chunk) => {
        doc.text(chunk, 20, y)
        y += 5
      })
    } else {
      doc.text(line, 20, y)
      y += 5
    }

    // If we're near the bottom of the page, create a new page
    if (y > 280) {
      doc.addPage()
      y = 20
    }
  })

  // Save the PDF
  doc.save(`${title.toLowerCase().replace(/\s+/g, "-")}.pdf`)
}
